# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChartWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChartWindow(object):
    def setupUi(self, ChartWindow):
        ChartWindow.setObjectName("ChartWindow")
        ChartWindow.resize(425, 513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChartWindow.setWindowIcon(icon)
        self.Chart = QtWidgets.QLabel(ChartWindow)
        self.Chart.setGeometry(QtCore.QRect(10, 20, 381, 471))
        self.Chart.setText("")
        self.Chart.setPixmap(QtGui.QPixmap("images/Chart.png"))
        self.Chart.setScaledContents(True)
        self.Chart.setObjectName("Chart")

        self.retranslateUi(ChartWindow)
        QtCore.QMetaObject.connectSlotsByName(ChartWindow)

    def retranslateUi(self, ChartWindow):
        _translate = QtCore.QCoreApplication.translate
        ChartWindow.setWindowTitle(_translate("ChartWindow", "Strategy Chart"))
